config:
  pre-game-time: 3
  game-time: 30

  mogura-cooldown-tick: 40

  mogura-init-location:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0

  player-init-location:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0


  spectator-init-location:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0